### PR TITLE
use vs 2015

### PR DESCRIPTION
**Pull request by fgregg**
Hi @kmike I think this will direct appveyor to use msvc 2015. I think that the wheels should just work.

### CODE REVIEW

**Comment by kmike** [comment]
Hey @fgregg! It still fails: https://ci.appveyor.com/project/kmike/python-crfsuite/build/1.0.3/job/nxcbmrd43qsvg71j. Suspicious line in a log - it looks like VC:

> C:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe

**Comment by kmike** [comment]
It depends on a Python version: for Python 3.4 VC 10 is used; for Python 3.5 package builds correctly (using msvc 2015), but the test fails. It looks like test-only issue though.

**Comment by fgregg** [comment]
Yeah, reading more it seems like you have to use the version of msvc that python was compiled against. http://timcera.bitbucket.org/posts/appveyor_finally.html

So, I think fixes we'll have to made upstream on crfsuite to get this to work for python versions before 3.5

**Comment by fgregg** [comment]
Got a little but further by including msintypes https://ci.appveyor.com/project/fgregg/python-crfsuite/build/job/qe73j23utd1qqw8v https://github.com/datamade/python-crfsuite/commit/12dc235a76cb83f34764ba7086ca1014b02324b1

**Comment by fgregg** [comment]
I think related to this. https://github.com/chokkan/crfsuite/commit/a5221daa150ecddb4f0656033275e4a1f91effd9#diff-9d04ba41c1c8bdc56a7fb9cb75ff7f71L49

**Pull request merged**
